### ISSUE TITLE
remove unauthorized, unverified and outdated uBlock Origin "marketing" website, binaries, and Safari Extension Gallery Listing

### ISSUE THREAD

**Issue by vassudanagunta** [hartator/uBlock-Safari#1]
See el1t/uBlock-Safari#69 for complete details and discussion.

**Comment by Atavic** [comment]
Hasn't this at least been verified? In the link, Gorhill says:

>In short, nothing bad in the Apple store version.

**Comment by Atavic** [comment]
Do Hartator and el1t have different versions uploaded?

**Comment by hartator** [comment]
@Atavic, no, it's exactly the same one as @el1t. Except the logo where I've created a HD version of it as required by Apple.

**Comment by Atavic** [comment]
:+1:

**Comment by vassudanagunta** [comment]
@Atavic, yes, it's been verified but still outdated and unauthorized. Gorhill also says:

> However, it is a dated one, and from what I understand, the most pressing issue is that it's getting in the way of the official one from being updated.
>
> Aside this, there is the fact that the extension in the store fail to disclose that it is not published by the official maintainer of the extension

As to [the "marketing" website](https://hartator.github.io/uBlock-Safari/)... there already is an official uBlock Origin website: https://github.com/gorhill/uBlock. It's what even Wikipedia points to. Creating other sites just adds noise and confusion. If people want to make the official site prettier, they should work with @gorhill, IMHO.

**Comment by vassudanagunta** [comment]
closing as this project looks dead.
